### ISSUE TITLE
cinnamon: Pressing the power button while screen is locked prevents later shutdown or reboot

### ISSUE THREAD

**Issue by tilkov** [linuxmint/mint22.1-beta#108]
Hi everyone,

When the power button setting is set to Ask (the default), on pressing it, the system pops up a prompt what to do: shutdown, reboot, etc.
If the screen is locked (Ctl + Alt + L) and the power button is pressed, nothing happens. Later, when the screen is unlocked, neither the power button, nor the shutdown button present this popup and the system cannot be shutdown/rebooted by the normal means.

Looking glass says: warning t=2025-01-04T21:31:01Z End session dialog already exists

**Comment by kuehhe1** [comment]
I can confirm the message from @Tillkov.
The power button shows the same behavior when the screen is locked.

The last Looking Glass feedback after checking the power settings whether the power button is set to “Ask”:
```
info t=2025-01-04T21:22:55Z Loaded applet power@cinnamon.org in 43 ms
warning t=2025-01-04T21:22:55Z 
QRedshift: Created
warning t=2025-01-04T21:22:55Z 
QRedshift: ADDED TO PANEL
info t=2025-01-04T21:22:55Z Loaded applet qredshift@quintao in 39 ms
```

System:
```
kuehhe1@LM22-1-Cin-Test:~$ inxi -SM
System:
  Host: LM22-1-Cin-Test Kernel: 6.8.0-51-generic arch: x86_64 bits: 64
  Desktop: Cinnamon v: 6.4.3 Distro: Linux Mint 22.1 Xia
Machine:
  Type: Laptop System: HP product: HP ProBook 470 G5 v: SBKPF
    serial: <superuser required>
  Mobo: HP model: 837F v: KBC Version 02.41.00 serial: <superuser required>
    UEFI: HP v: Q85 Ver. 01.28.00 date: 04/11/2024
kuehhe1@LM22-1-Cin-Test:~$ 
```


Translated with DeepL.com (free version)
